name: Build+Test+Lint
on:
  push:
    branches: [master, thlorenz/accounts]
  pull_request:
    branches: [master]

jobs:
  build-test-lint:
    runs-on:
      group: Default
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node-version: [18.x]

    steps:
      - uses: actions/checkout@master

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Build
        run: yarn build
        shell: bash

      - name: Test
        run: yarn test
        shell: bash

      - name: Lint
        run: yarn lint
        shell: bash
